export * from "./Header/Header";
export * from "./GenreBadge/GenreBadge";
export * from "./Genres/Genres";
export * from "./MovieInfo/MovieInfo";
export * from "./MoviesList/MoviesList";
export * from "./MoviesListCard/MoviesListCard";
export * from "./SearchMovies/SearchMovies";
export * from "./Main/Main";
export * from "./Layout/Layout";